### ISSUE TITLE
cannot build with java 20 nor java 21

### ISSUE THREAD

**Issue by maxandersen** [padreati/rapaio-jupyter-kernel#38]
with java 20 I get:

```
[ERROR] Errors: 
[ERROR]   MagicEngineTest.magicJarsEvalTest:53 » MagicEval Provided path does not exist.
[INFO] 
[ERROR] Tests run: 27, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
```

and Java 21 gives me a lot of these:

```
You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [class org.rapaio.jupyter.kernel.channels.Channels, class java.lang.Object]
[ERROR]   LoadMagicHandlerTest.loadNotebook:203 » Mockito 
Mockito cannot mock this class: class org.rapaio.jupyter.kernel.channels.Channels.
Can not mock final classes with the following settings :
 - explicit serialization (e.g. withSettings().serializable())
 - extra interfaces (e.g. withSettings().extraInterfaces(...))

You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

```

**Comment by padreati** [comment]
Looking into it.

**Comment by padreati** [comment]
For example mine looks like:

```
$ java --version
openjdk 20.0.1 2023-04-18
OpenJDK Runtime Environment Corretto-20.0.1.9.1 (build 20.0.1+9-FR)
OpenJDK 64-Bit Server VM Corretto-20.0.1.9.1 (build 20.0.1+9-FR, mixed mode, sharing)

```
(base) tutuianu@u31509ccf96855b:/home/ati/work/rapaio-jupyter-kernel$ mvn clean
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] 
[INFO] --------------< io.github.padreati:rapaio-jupyter-kernel >--------------
[INFO] Building rapaio-jupyter-kernel 1.2.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ rapaio-jupyter-kernel ---
[INFO] Deleting /home/ati/work/rapaio-jupyter-kernel/target
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.740 s
[INFO] Finished at: 2023-07-24T11:28:27+03:00
[INFO] ------------------------------------------------------------------------
(base) tutuianu@u31509ccf96855b:/home/ati/work/rapaio-jupyter-kernel$ mvn install
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] 
[INFO] --------------< io.github.padreati:rapaio-jupyter-kernel >--------------
[INFO] Building rapaio-jupyter-kernel 1.2.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ rapaio-jupyter-kernel ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.11.0:compile (default-compile) @ rapaio-jupyter-kernel ---
[INFO] Changes detected - recompiling the module! :source
[INFO] Compiling 122 source files with javac [debug release 20] to target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ rapaio-jupyter-kernel ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/ati/work/rapaio-jupyter-kernel/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.11.0:testCompile (default-testCompile) @ rapaio-jupyter-kernel ---
[INFO] Changes detected - recompiling the module! :dependency
[INFO] Compiling 14 source files with javac [debug release 20] to target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0:test (default-test) @ rapaio-jupyter-kernel ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.rapaio.jupyter.kernel.global.GlobalTest
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.367 s - in org.rapaio.jupyter.kernel.global.GlobalTest
[INFO] Running org.rapaio.jupyter.kernel.core.ConnectionPropertiesTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.079 s - in org.rapaio.jupyter.kernel.core.ConnectionPropertiesTest
[INFO] Running org.rapaio.jupyter.kernel.core.magic.handlers.JarMagicHandlerTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.172 s - in org.rapaio.jupyter.kernel.core.magic.handlers.JarMagicHandlerTest
[INFO] Running org.rapaio.jupyter.kernel.core.magic.handlers.LoadMagicHandlerTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.248 s - in org.rapaio.jupyter.kernel.core.magic.handlers.LoadMagicHandlerTest
[INFO] Running org.rapaio.jupyter.kernel.core.magic.MagicParserTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.01 s - in org.rapaio.jupyter.kernel.core.magic.MagicParserTest
[INFO] Running org.rapaio.jupyter.kernel.core.magic.MagicEngineTest
org.rapaio.jupyter.kernel.core.display.DisplayData@4693a9ef
org.rapaio.jupyter.kernel.core.display.DisplayData@2f4b98f6
MagicCompleteResult[handled=true, replacementOptions=CompleteMatches[replacements=[%%bash, %%jars, %classpath , %help, %image , %jar, %jshell /imports, %jshell /list, %jshell /list , %jshell /list -all, %jshell /methods, %jshell /types, %jshell /vars, %load , %maven ], start=0, end=6]]
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.336 s - in org.rapaio.jupyter.kernel.core.magic.MagicEngineTest
[INFO] Running org.rapaio.jupyter.kernel.core.format.OutputFormatterTest
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

   at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
   at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
   at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
   at java.base/java.util.Objects.checkIndex(Objects.java:385)
   at java.base/java.util.ArrayList.get(ArrayList.java:427)
   at .g(#3:2)
|    String g(int p) {
|-->     return list.get(p);
|    }
   at .(#5:1)
|--> g(0);
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.149 s - in org.rapaio.jupyter.kernel.core.format.OutputFormatterTest
[INFO] Running org.rapaio.jupyter.kernel.core.display.text.ANSITextTest
|    for(int i=0; i<10; i++) {
|        y=12;
|    }
cannot find symbol
  symbol:   variable y

[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.036 s - in org.rapaio.jupyter.kernel.core.display.text.ANSITextTest
[INFO] Running org.rapaio.jupyter.kernel.core.display.image.ImageHandlerTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.925 s - in org.rapaio.jupyter.kernel.core.display.image.ImageHandlerTest
[INFO] Running org.rapaio.jupyter.kernel.core.display.html.tags.TagsTest

[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.071 s - in org.rapaio.jupyter.kernel.core.display.html.tags.TagsTest
[INFO] Running org.rapaio.jupyter.kernel.core.java.JavaEngineTest
test
CompleteMatches[replacements=[System], start=0, end=3]
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.168 s - in org.rapaio.jupyter.kernel.core.java.JavaEngineTest
[INFO] Running org.rapaio.jupyter.kernel.core.RapaioKernelTest
Jul 24, 2023 11:28:41 AM org.rapaio.jupyter.kernel.channels.ControlChannel bind
INFO: [ControlChannel]: Binding to tcp://127.0.0.1:60001
Jul 24, 2023 11:28:41 AM org.rapaio.jupyter.kernel.channels.HeartbeatChannel bind
INFO: [HeartbeatChannel]: Binding to tcp://127.0.0.1:60004
Jul 24, 2023 11:28:41 AM org.rapaio.jupyter.kernel.channels.HeartbeatChannel bind
INFO: [HeartbeatChannel]: Polling on Heartbeat-0
Jul 24, 2023 11:28:41 AM org.rapaio.jupyter.kernel.channels.ShellChannel bind
INFO: [ShellChannel]: Binding to tcp://127.0.0.1:60002
Jul 24, 2023 11:28:41 AM org.rapaio.jupyter.kernel.channels.IOPubChannel bind
INFO: [IOPubChannel]: Binding iopub to tcp://127.0.0.1:60005
Jul 24, 2023 11:28:41 AM org.rapaio.jupyter.kernel.channels.StdinChannel bind
INFO: [StdinChannel]: Binding stdin to tcp://127.0.0.1:60003
Jul 24, 2023 11:28:41 AM org.rapaio.jupyter.kernel.channels.ShellChannel bind
INFO: [ShellChannel]: Binding to tcp://127.0.0.1:60002
Jul 24, 2023 11:28:41 AM org.rapaio.jupyter.kernel.channels.HeartbeatChannel bind
INFO: [HeartbeatChannel]: Binding to tcp://127.0.0.1:60004
Jul 24, 2023 11:28:41 AM org.rapaio.jupyter.kernel.channels.HeartbeatChannel bind
INFO: [HeartbeatChannel]: Polling on Heartbeat-1
Jul 24, 2023 11:28:41 AM org.rapaio.jupyter.kernel.channels.IOPubChannel bind
INFO: [IOPubChannel]: Binding iopub to tcp://127.0.0.1:60005
Jul 24, 2023 11:28:41 AM org.rapaio.jupyter.kernel.channels.StdinChannel bind
INFO: [StdinChannel]: Binding stdin to tcp://127.0.0.1:60003
Jul 24, 2023 11:28:41 AM org.rapaio.jupyter.kernel.channels.ControlChannel bind
INFO: [ControlChannel]: Binding to tcp://127.0.0.1:60001
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.269 s - in org.rapaio.jupyter.kernel.core.RapaioKernelTest
[INFO] Running org.rapaio.jupyter.kernel.extension.JupyterDisplayableTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in org.rapaio.jupyter.kernel.extension.JupyterDisplayableTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 27, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ rapaio-jupyter-kernel ---
[INFO] Building jar: /home/ati/work/rapaio-jupyter-kernel/target/rapaio-jupyter-kernel-1.2.1.jar
[INFO] 
[INFO] --- maven-assembly-plugin:2.2-beta-5:single (default) @ rapaio-jupyter-kernel ---
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/ already added, skipping
[INFO] META-INF/maven/ already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/ already added, skipping
[INFO] com/ already added, skipping
[INFO] META-INF/maven/ already added, skipping
[INFO] META-INF/ already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] org/ already added, skipping
[INFO] Building jar: /home/ati/work/rapaio-jupyter-kernel/target/rapaio-jupyter-kernel-1.2.1.jar
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/ already added, skipping
[INFO] META-INF/maven/ already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] META-INF/ already added, skipping
[INFO] com/ already added, skipping
[INFO] META-INF/maven/ already added, skipping
[INFO] META-INF/ already added, skipping
[INFO] META-INF/MANIFEST.MF already added, skipping
[INFO] org/ already added, skipping
[WARNING] Configuration options: 'appendAssemblyId' is set to false, and 'classifier' is missing.
Instead of attaching the assembly file: /home/ati/work/rapaio-jupyter-kernel/target/rapaio-jupyter-kernel-1.2.1.jar, it will become the file for main project artifact.
NOTE: If multiple descriptors or descriptor-formats are provided for this project, the value of this file will be non-deterministic!
[WARNING] Replacing pre-existing project main-artifact file: /home/ati/work/rapaio-jupyter-kernel/target/rapaio-jupyter-kernel-1.2.1.jar
with assembly file: /home/ati/work/rapaio-jupyter-kernel/target/rapaio-jupyter-kernel-1.2.1.jar
[INFO] 
[INFO] --- maven-javadoc-plugin:3.4.1:jar (attach-javadocs) @ rapaio-jupyter-kernel ---
[INFO] No previous run data found, generating javadoc.
[INFO] Building jar: /home/ati/work/rapaio-jupyter-kernel/target/rapaio-jupyter-kernel-1.2.1-javadoc.jar
[INFO] 
[INFO] --- maven-source-plugin:3.2.1:jar-no-fork (attach-sources) @ rapaio-jupyter-kernel ---
[INFO] Building jar: /home/ati/work/rapaio-jupyter-kernel/target/rapaio-jupyter-kernel-1.2.1-sources.jar
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ rapaio-jupyter-kernel ---
[INFO] Installing /home/ati/work/rapaio-jupyter-kernel/target/rapaio-jupyter-kernel-1.2.1.jar to /home/ANT.AMAZON.COM/tutuianu/.m2/repository/io/github/padreati/rapaio-jupyter-kernel/1.2.1/rapaio-jupyter-kernel-1.2.1.jar
[INFO] Installing /home/ati/work/rapaio-jupyter-kernel/pom.xml to /home/ANT.AMAZON.COM/tutuianu/.m2/repository/io/github/padreati/rapaio-jupyter-kernel/1.2.1/rapaio-jupyter-kernel-1.2.1.pom
[INFO] Installing /home/ati/work/rapaio-jupyter-kernel/target/rapaio-jupyter-kernel-1.2.1-javadoc.jar to /home/ANT.AMAZON.COM/tutuianu/.m2/repository/io/github/padreati/rapaio-jupyter-kernel/1.2.1/rapaio-jupyter-kernel-1.2.1-javadoc.jar
[INFO] Installing /home/ati/work/rapaio-jupyter-kernel/target/rapaio-jupyter-kernel-1.2.1-sources.jar to /home/ANT.AMAZON.COM/tutuianu/.m2/repository/io/github/padreati/rapaio-jupyter-kernel/1.2.1/rapaio-jupyter-kernel-1.2.1-sources.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.859 s
[INFO] Finished at: 2023-07-24T11:28:47+03:00
[INFO] ------------------------------------------------------------------------
