### ISSUE TITLE
Support for Java 17 / Java 21?

### ISSUE THREAD

**Issue by rgemulla** [padreati/rapaio-jupyter-kernel#72]
The current release requires Java 22 or above, which means that this package cannot be used on systems running Java 17 or Java 21 (the two most recent LTS releases). Is there any way to use this kernel on such systems?

**Comment by padreati** [comment]
Currently the only way is to rebuild it for 17 version and change the compiler options in kernel.json. I had put the latest version because I enable preview features, which I use in a library that I own. But actually there is no need for such constraint.

In order to make things easy I will create a new release which will allow an optional auto installer. I will see how low I can go with java release. Thank you for trying, I will solve this issue in the following days. Hope that helps.

**Comment by rgemulla** [comment]
Dear @padreati, that would be great, thanks a lot!

**Comment by padreati** [comment]
I have implemented the changes for enabling Java 17 and above. In order to facilitate using custom setups I have created also an installer profile. The default profile runs clean, as expected. There are two additional profiles, preview22 and preview23 which creates kernel.json files configured for using preview features with java 22 and 23. This will catch the next release which will come soon.

**Comment by padreati** [comment]
Resolved. To be released in 2.2.0

**Comment by rgemulla** [comment]
Great, thank you very much! I'll provide feedback once the release is out.

**Comment by rgemulla** [comment]
Works flawlessly for me, thanks!
