### ISSUE TITLE
example.ipynb: Could not resolve dependencies... javafaker

### ISSUE THREAD

**Issue by BigFlagBurito** [padreati/rapaio-jupyter-kernel#74]
Hello,
I have installed the kernel (version 2.2.0, -auto, -system) and OpenJDK (21.0.5).
When running the _example.ipynb_ the following errors occur:
`Could not resolve dependencies.Failed to collect dependencies at com.github.javafaker:javafaker:jar:1.0.2`
`Could not resolve dependencies.Failed to collect dependencies at com.google.guava:guava:jar:20.0`

I can't figure out what the problem is.
I hope you can help me.

**Comment by padreati** [comment]
Hi, could you tell me some additional info?

- what is the output of `java --help`?
- which is the content of `kernel.json` file?
- what os are you using?

Best regards

**Comment by padreati** [comment]
Sorry, I was trying to say `java --version`, it is my mistake. Thank you a lot

**Comment by padreati** [comment]
All those minor versions looks identical, like on my host (even the os). The only thing which remains is to see the logs of the notebook server. I suppose that you are using `jupyter --notebook` or `jupyter-lab`. If that is the case you probably lauch it from command line. In that case would it be possible that you put here all the logs from notebook command line when you open the `example.ipynb` and run it with those errors? I know is an effort, but I see no other way to understand what is going on. Thank you a lot!

**Comment by padreati** [comment]
I know nothing about JupyterHub. I will do my homework and came back a solution. Thank you

**Comment by padreati** [comment]
One thing which might be a problem is related with user permissions. 

In order to collect dependencies I use MIMA (MInimal MAven). This uses a local cache for dependencies in order to not collect dependencies multiple times or to avoid dowloading them every time. This is basically what maven does. The kernel creates a directory for that purpose. This directory is called `mima_cache` in is created in the folder where the kernel resides, which should be in your case `/usr/share/jupyter/kernels/rapaio-jupyter-kernel/`.  

I did not implemented a configuration feature for that (this is actually a good idea of a feature, there is something related with configurations in issues). So this cannot be changed. But what can be changed is to install the kernel in another folder (one way would be to not use `-system` option, so it will go somewhere in home folder `~/.local/share/jupyter/kernels` where the user should have proper permissions) or simply to try to give permissions over that folder. 

Perhaps you could try to test this hypothesis to see if it can work. Best regards.

**Comment by padreati** [comment]
Thank you a lot. I will create an issue with a feature proposal for a configurable mima cache folder and also investigate the error to make it shown in notebook.
